# Generated by Django 4.1.5 on 2023-01-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0002_personel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
