# Generated by Django 4.1.5 on 2023-01-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0005_personal_delete_personel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='salary',
            field=models.SmallIntegerField(),
        ),
    ]
